-- AlterTable
ALTER TABLE "LlmUsage" ADD COLUMN IF NOT EXISTS "cacheReadTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LlmUsage" ADD COLUMN IF NOT EXISTS "cacheCreation5mTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LlmUsage" ADD COLUMN IF NOT EXISTS "cacheCreation1hTokens" INTEGER NOT NULL DEFAULT 0;
